name: Daily ETL Execution

on:
  schedule:
    # Runs at 7:00 am every day (UTC time)
    - cron: '0 7 * * *'
  workflow_dispatch:  # Enables manual triggering

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Execute ETL script
        run: |
          python etl.py

      - name: Configure Git for commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add duchenne_studies_sample.json duchenne_studies_sample.csv duchenne_studies_history.csv
          git commit -m "Automatic update of ETL data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
